language: python

services:
  - docker

before_script: pip install docker-compose

script: if [[ "$TRAVIS_BRANCH" == "main" ]]; then
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  docker-compose build ;
  docker tag api $DOCKER_USERNAME/danksongs-api:latest ;
  docker tag ui $DOCKER_USERNAME/danksongs-ui:latest ;
  docker push $DOCKER_USERNAME/danksongs-api:latest ;
  docker push $DOCKER_USERNAME/danksongs-ui:latest ;
  fi

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: danksongs-prod
  env: Danksongsprod-env
  bucket-name: elasticbeanstalk-ap-southeast-2-199561299566
  bucket-path: danksongs
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
