version: "3.4"

services:
  # Backend golang server
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: danksongs-api
    ports:
      - "8080:8080"
    environment:
      - MONGOUSERNAME="${MONGOUSERNAME}"
      - DATABASENAME="${DATABASENAME}"
      - MONGOPWD="${MONGOPWD}"
    restart: always
    links:
      - mongo
  # MongoDB database
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=danksongs
      - MONGO_INITDB_ROOT_PASSWORD=locked1234
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    restart: always
  # MongoDB WebUI
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=danksongs
      - ME_CONFIG_MONGODB_ADMINPASSWORD=locked1234
      - ME_CONFIG_BASICAUTH_USERNAME=danksongs
      - ME_CONFIG_BASICAUTH_PASSWORD=locked1234
    restart: always
    ports:
      - "8081:8081"
  # React frontend
  ui:
    build: ./ui
    container_name: danksongs-ui
    ports:
      - "3000:3000"
    restart: always
    links:
      - api
