version: "3.4"

services:
  # Backend golang server
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: danksongs-api
    ports:
      - "8080:8080"
    environment:
      - MONGOUSERNAME="${MONGOUSERNAME}"
      - DATABASENAME="${DATABASENAME}"
      - MONGOPWD="${MONGOPWD}"
    restart: always
    links:
      - mongo
  # MongoDB database
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    restart: always
  # React frontend
  ui:
    build: ./ui
    container_name: danksongs-ui
    ports:
      - "3000:3000"
    restart: always
    links:
      - api

volumes:
  mongodb_data:
