version: "3.4"

services:
  # Backend golang server
  server:
    build:
      context: .
    image: mitchrule/danksongs-server
    container_name: danksongs-server
    ports:
      - "80:80"
    restart: always
    links:
      - mongo
    mem_limit: 512m

  # MongoDB database
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
    mem_limit: 256m
    logging:
      driver: none

volumes:
  mongodata:
