version: "3.4"

services:
  # Backend golang server
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: danksongs-api
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongo

  # MongoDB database
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    restart: always
    logging:
      driver: "none"

  # MongoDB WebUI
  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    logging:
      driver: "none"

  # React frontend
  ui:
    build: ./ui
    container_name: danksongs-ui
    ports:
      - "3000:3000"
    restart: always
    links:
      - api
