version: "3.4"

services:
  # Backend golang server
  server:
    build:
      context: ./backend
    image: mitchrule/danksongs-server
    container_name: danksongs-server
    env_file: .env
    ports:
      - "80:80"

    restart: always
    links:
      - mongo
    mem_limit: 512m

  # next.js ui
  ui:
    build:
      context: ./ui
    image: danksongs/danksongs-ui
    container_name: danksongs-ui
    ports:
      - "81:3000"
    restart: always
    links:
      - server
    mem_limit: 256m

  # MongoDB database
  mongo:
    image: "mongo:latest"
    logging:
      driver: none
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
    mem_limit: 256m
    logging:
      driver: none

volumes:
  mongodata:
