version: "3.4"

services:
  # Backend golang server
  api:
    build:
      context: ./backend
    image: mitchrule/danksongs-api
    container_name: danksongs-api
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongo
    mem_limit: 256m

  # MongoDB database
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
    mem_limit: 256m
    # logging:
    # driver: "none"

  # # MongoDB WebUI
  # mongo-express:
  #   image: mongo-express
  #   container_name: "mongo-express"
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mongo
  #   mem_limit: 128m
  # logging:
  # driver: "none"

  # React frontend
  ui:
    build:
      context: ./ui
    image: mitchrule/danksongs-ui
    container_name: danksongs-ui
    ports:
      - "80:3000"
    restart: always
    links:
      - api
    mem_limit: 256m

volumes:
  mongodata:
